name: 'PR SUMMARY validator'
description: 'Validate that PR descriptions contain a matching SUMMARY entry,'
author: 'KevinGranade'
inputs:
  description-regex:
    description: 'Description regex to match'
    required: true
    default: '.*SUMMARY:.*'
  description-regex-flags:
    description: 'Flags for the description regex'
    required: false
    default: ''
runs:
  using: 'node12'
  main: 'lib/main.js'
  
